#!/bin/bash

set -e

VERSION=0.6.2
URL=https://github.com/bemasher/rtlamr/releases/download/v${VERSION}/rtlamr_linux_amd64.tar.gz
NAME=rtlamr

OUT=$(pwd)/out
mkdir -p $OUT

echo "--> Downloading $NAME $VERSION"
curl -sLo /tmp/$NAME.tgz $URL
echo "--> Extracting $NAME"
mkdir -p /tmp/rtlamr
cd /tmp/rtlamr && tar -xvf ../$NAME.tgz
echo '--> Building deb package'
mkdir -p usr/bin
mv rtlamr usr/bin/
rm *
cd $OUT
bundle exec fpm -s dir -t deb -n $NAME -v $VERSION -C /tmp/rtlamr \
  -p ${NAME}_VERSION_ARCH.deb \
  -d "librtlsdr > 0" \
  usr/bin
