#!/bin/bash

set -e

if [ -z "$PACKAGECLOUD_TOKEN" ]; then
    echo "--> PACKAGECLOUD_TOKEN is unset";
    exit 1
fi

gem install package_cloud
for f in $(ls out/*.deb); do
    package_cloud push lstoll/packages/ubuntu/trusty $f | tee /tmp/pkgout
    if [ $? != 0 ]; then
	if ! grep -q "filename: has already been taken" /tmp/pkgout; then
	    echo "Error occured while pushing package, exiting"
	    exit 1
	fi
    fi
done
